// <auto-generated />
using Discount.Grpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountContext))]
    [Migration("20250715172909_InitalCreate")]
    partial class InitalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Discount.Grpc.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5000,
                            Description = "Flat discount on all laptops",
                            ProductName = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 2000,
                            Description = "Discount on selected smartphones",
                            ProductName = "Mobile"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 500,
                            Description = "Limited time headphone offer",
                            ProductName = "Headphones"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 300,
                            Description = "10% off on mechanical keyboards",
                            ProductName = "Keyboard"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 1500,
                            Description = "Festival offer on monitors",
                            ProductName = "Monitor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
